# Generated by Django 2.0.13 on 2019-03-16 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=3)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_metadata_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
