# Generated by Django 2.0.13 on 2019-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('url', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('epigrafe', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
