# Generated by Django 2.0.13 on 2019-03-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('slug', models.SlugField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
